<?php
/**
 * @file
 * Decreto Dashboard module.
 */

/**
 * Implements hook_menu().
 */
function decreto_dash_menu() {
  $items['dashboard'] = array(
    'title' => 'Home',
    'page callback' => 'decreto_dash_home',
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}

/**
 * Dashboard home page callback.
 */
function decreto_dash_home() {
  $variables = array(
    'blocks' => decreto_dash_get_user_blocks(),
  );

  return theme('decreto_dash_home', $variables);
}

/**
 * Implements hook_theme().
 */
function decreto_dash_theme() {
  return array(
    'decreto_dash_home' => array(
      'template' => 'decreto-dash-home',
      'arguments' => array(
        'blocks' => array(),
      ),
      'path' => drupal_get_path('module', 'decreto_dash') . '/templates',
    ),
  );
}

/**
 * Get users blocks for dashboard.
 */
function decreto_dash_get_user_blocks() {
  $blocks = array();

  $calendar = render(views_embed_view('meeting_calendar', 'block'));
  $blocks[] = '<h3>Kalender</h3>' . $calendar;

  $upcoming = render(views_embed_view('meeting_calendar', 'upcoming'));
  $blocks[] = '<h3>Kommende møder</h3>' . $upcoming;

  $blocks[] = '<h3>Driftstatus</h3><div class="alert alert-success" role="alert">Alt er godt.</div>';

  return $blocks;
}
