<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    $vendorDir . '/igorw/get-in/src/get_in.php',
    $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
);
