<?php
/**
 * @file
 * Decreto user module.
 */

/**
 * Implements hook_form_alter().
 */
function decreto_user_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  // Only users with the correct permissions should be able to change these
  // options on the user.
  if (!user_access('administer users')) {
    $form['field_committee_admin']['#access'] = FALSE;
    $form['field_committee_reference']['#access'] = FALSE;
    $form['field_company_admin']['#access'] = FALSE;
    $form['field_company_reference']['#access'] = FALSE;
    $form['field_company']['#access'] = FALSE;
  }
}

/**
 * Implements hook_user_login().
 */
function decreto_user_user_login(&$edit, $account) {
  // Send the user to the dashboard.
  $edit['redirect'] = 'dashboard';
}

/**
 * Implements hook_init().
 */
function decreto_user_init() {
  if (user_is_logged_in() && drupal_is_front_page()) {
    drupal_goto('dashboard');
  }
}

/**
 * Implements hook_custom_theme().
 */
function decreto_user_custom_theme() {
  // Use decreto_frontend theme, when not logged in
  if (user_is_anonymous()) {
    return 'decreto_frontend';
  }
}